# Generated by Django 5.1.2 on 2024-10-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('numero_container', models.CharField(max_length=11, unique=True)),
                ('tipo', models.CharField(choices=[('20', '20'), ('40', '40')], max_length=2)),
                ('status', models.CharField(choices=[('Cheio', 'Cheio'), ('Vazio', 'Vazio')], max_length=5)),
                ('categoria', models.CharField(choices=[('Importação', 'Importação'), ('Exportação', 'Exportação')], max_length=12)),
            ],
        ),
    ]
